apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1-redis
  namespace: redis
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: "17.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: standalone
