apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      chart: ""
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: nginx
  interval: 1m0s
  targetNamespace: nginx
  values: {}
