apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app2-nginx
  namespace: nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "13.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: ClusterIP
