apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  releaseName: rook-ceph
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.16.4
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    remediation:
      retries: 3
  # Default values https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml
  values:
    enableDiscoveryDaemon: true
    monitoring:
      enabled: true