apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capacitor
  namespace: flux-system
spec:
  releaseName: capacitor
  interval: 5m
  chart:
    spec:
      chart: capacitor
      sourceRef:
        kind: OCIRepository
        name: capacitor
  # Default values https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml