apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  releaseName: renovate
  interval: 5m
  chart:
    spec:
      chart: renovate
      sourceRef:
        kind: HelmRepository
        name: renovate
  # Default values https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml