apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook
  namespace: rook
spec:
  releaseName: rook
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  # Default values https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml
  values:
    monitoring:
      enabled: true