apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 10m
  url: https://github.com/renovatebot/renovate
  ref:
    tag: v11.35.4
