apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podtato-head
  namespace: podtato-head
spec:
  targetNamespace: podtato-head
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: podtato-head