# There is no `kind: OCIRelease`, so the `kind: Kustomization` must be used to apply resources from an OCI repository.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: capacitor
spec:
  targetNamespace: capacitor
  interval: 10m
  wait: true
  prune: true
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: capacitor